-- Creating category table.
CREATE TABLE category (
category_id INT PRIMARY KEY,
category_name VARCHAR(20)
);

-- Creating customers table
DROP TABLE IF EXISTS customers;
CREATE TABLE customers (
customer_id INT PRIMARY KEY,
first_name VARCHAR(20),
last_name VARCHAR(20),
state VARCHAR(20),
address VARCHAR(5)
);

-- Creat sellers table.
CREATE TABLE sellers (
seller_id INT PRIMARY KEY,
seller_name VARCHAR(25),
origin VARCHAR(10)
);

-- Create products table
CREATE TABLE products (
product_id INT PRIMARY KEY,
product_name VARCHAR(50),
price FLOAT,
cogs FLOAT,
category_id INT, 
CONSTRAINT fk_products_category_id FOREIGN KEY (category_id) REFERENCES category(category_id)
);

-- Creat orders table.
CREATE TABLE orders (
order_id INT PRIMARY KEY,
order_date DATE,
customer_id INT,
seller_id INT,
order_status VARCHAR(15),
CONSTRAINT fk_orders_customer_id FOREIGN KEY (customer_id) REFERENCES customers(customer_id),
CONSTRAINT fk_orders_seller_id FOREIGN KEY (seller_id) REFERENCES sellers(seller_id)
);

-- Create order_items table.
CREATE TABLE order_items (
order_item_id INT PRIMARY KEY,
order_id INT,
product_id INT,
quantity INT,
price_per_unit FLOAT,
CONSTRAINT fk_order_items_order_id FOREIGN KEY (order_id) REFERENCES orders(order_id),
CONSTRAINT fk_order_items_product_id FOREIGN KEY (product_id) REFERENCES products(product_id)
);

-- Creat payments table.
CREATE TABLE payments (
payment_id INT PRIMARY KEY,
order_id INT,
payment_date DATE,
payment_status VARCHAR(20),
CONSTRAINT fk_payments_order_id FOREIGN KEY (order_id) REFERENCES orders(order_id)
);

-- Creat shippings table.
CREATE TABLE shippings (
shipping_id INT PRIMARY KEY,
order_id INT,
shipping_date DATE,
return_date DATE,
shipping_providers VARCHAR(15),
delivery_status VARCHAR(15),
CONSTRAINT fk_shippings_order_id FOREIGN KEY (order_id) REFERENCES orders(order_id)
);

-- Creat inventory table.
CREATE TABLE inventory (
inventory_id INT,
product_id INT,
stock INT,
warehouse_id INT,
last_stock_date DATE,
CONSTRAINT fk_inventory_product_id FOREIGN KEY (product_id) REFERENCES products(product_id)
);

-- EDA



-- Business Questions
-- Advance Analysis
/* Q.1 Query the top 10 products by total sales value.
Challenge: Include product name, total_quantity sold, and total sales value.
*/

-- First of all, we create a column for total sales as quantity*price_per_unit in order_items table.
ALTER TABLE order_items
ADD COLUMN total_sales FLOAT;

UPDATE order_items
SET total_sales=quantity*price_per_unit;

-- Answer
SELECT oi.product_id, p.product_name, sum(oi.quantity) AS total_quantity, 
		sum(oi.total_sales) AS total_sales
FROM orders AS o
LEFT JOIN order_items AS oi ON o.order_id=oi.order_id
LEFT JOIN products AS p ON p.product_id=oi.product_id 
GROUP BY 1, 2
ORDER BY total_sales DESC
LIMIT 10;

/* Q.2 Calculate total revenue generated by each product category.
Challenge: Include the percentage contribution of each category to total revenue.
*/
-- Answer
SELECT  p.category_id, c.category_name, sum(oi.total_sales) AS total_revenue, 
	100*sum(oi.total_sales)/(SELECT sum(total_sales) FROM order_items) AS percent_contribution
FROM order_items AS oi
LEFT JOIN products AS p ON p.product_id=oi.product_id
LEFT JOIN category AS c ON p.category_id= c.category_id
GROUP BY 1, 2
ORDER BY 1;


/* Q.3 Compute the average order value for each customer.
Challenge: Include only customers with more than 5 orders.
*/
-- Answer
SELECT c.customer_id, count(o.order_id) AS order_value, sum(oi.total_sales)
FROM customers AS c
JOIN orders AS o ON c.customer_id=o.customer_id
JOIN order_items AS oi ON oi.order_id=o.order_id
GROUP BY c.customer_id
HAVING count(o.order_id)>5
ORDER BY c.customer_id DESC;


/* Q.4 Montly Sales Trend
Query montly total sales over the past year.
Challenge; Display the sales trend, grouping by month, return current_month sale, last month sale.
*/
-- Answer
WITH last_year_sales AS (SELECT count(pay.order_id) AS total_orders, 
		EXTRACT(MONTH FROM payment_date) AS month, 
EXTRACT(YEAR FROM payment_date) AS YEAR, ROUND(sum(oi.total_sales)::NUMERIC, 2) AS total_sales
FROM payments AS pay
LEFT JOIN order_items AS oi ON pay.order_id=oi.order_id
WHERE pay.payment_status='Payment Successed' AND 
	payment_date >= (SELECT max(payment_date) FROM payments) - INTERVAL '1 YEAR'
GROUP BY 2, 3)
SELECT month, year, total_sales AS current_month_sales, 
		LAG(total_sales, 1) OVER (ORDER BY year DESC, month DESC) AS last_month_sales
FROM last_year_sales;

SELECT DISTINCT payment_status FROM payments;


/* Q.5 Find customers who have registered but never placed an order.
Challenge: List customer details.
*/
-- Answer
SELECT c.customer_id, concat(c.first_name, ' ', c.last_name) AS customer_name, c.state
FROM customers AS c
LEFT JOIN orders AS o ON c.customer_id=o.customer_id
WHERE o.customer_id IS NULL
ORDER BY c.customer_id DESC;
--or 
SELECT customer_id, concat(first_name, ' ', last_name) AS customer_name, state
FROM customers
WHERE customer_id NOT IN (SELECT customer_id FROM orders)
ORDER BY customer_id DESC;


/* Q.6 Identify the least selling product category for each state.
Challenge: Include the total sales for what category within each sate.
*/
-- Answer
SELECT category_id, category_name 
FROM category; 

WITH state_category_sales AS (SELECT c.state, cat.category_name, 
					sum(oi.total_sales)::NUMERIC AS total_sales, 
			RANK() OVER (PARTITION BY state ORDER BY sum(oi.total_sales) ASC) AS ranking
FROM order_items AS oi
JOIN orders AS o ON oi.order_id=o.order_id
JOIN products AS p ON p.product_id=oi.product_id
JOIN customers AS c ON c.customer_id=o.customer_id
JOIN category AS cat ON cat.category_id=p.category_id
GROUP BY 1, 2
ORDER BY c.state)
SELECT state, category_name, total_sales, ranking
FROM state_category_sales
WHERE ranking=1;


/* Q.7 Calculate the total value of orders placed by each customer over their lifetime.
Challenge: Rank customers based on their customer life time value (CLTV).
*/
-- Answer



/* Q.9 Identity orders where the shipping date is later than 3 days after the order date.
Challenge: Include customer, order details, and delivery provider.
*/
-- Answer
SELECT o.order_id, CONCAT(c.first_name, ' ', c.last_name) AS customer_name, c.state AS customer_state, o.seller_id, o.order_date, s.shipping_date, 
							s.shipping_providers, o.order_status
FROM orders AS o
LEFT JOIN shippings AS s ON o.order_id=s.order_id
LEFT JOIN customers AS c ON c.customer_id=o.customer_id
WHERE s.shipping_date >= o.order_date + INTERVAL '3 DAYS' ;




/* Q.10 Calcualte the percentage of successful payments across all orders.
Challenge: Include breakdowns by payment status (e.g. failed, pending).
*/
-- Answer
SELECT count(o.order_id) AS total_orders, p.payment_status, 
		ROUND(100*count(o.order_id)::NUMERIC/(SELECT count(order_id) FROM payments), 2) AS percent
FROM orders AS o
JOIN payments AS p ON p.order_id=o.order_id
GROUP BY payment_status;


/* Q.11 Find the top 5 sellers based on total sales value.
Challenge: Include both successful and failed orders, and display their percentage of successful orders.
*/
-- Answer
WITH seller_sales AS (SELECT s.seller_id, s.seller_name, o.order_status,
			count(o.order_id) AS total_orders,ROUND(sum(oi.total_sales)::NUMERIC, 2) AS total_sales
FROM orders AS o
LEFT JOIN sellers AS s ON o.seller_id=s.seller_id
LEFT JOIN order_items AS oi ON oi.order_id=o.order_id
WHERE o.order_status IN ('Completed', 'Cancelled')
GROUP BY 1, 2,3
ORDER BY 1)
SELECT *, ROUND(100*total_orders/(SUM(total_orders) OVER (PARTITION BY seller_id)), 2) AS order_status_percentage
FROM seller_sales;

--or
WITH seller_sales AS (SELECT s.seller_id, s.seller_name, o.order_status, count(o.order_id) AS total_orders
FROM orders AS o
LEFT JOIN sellers AS s ON o.seller_id=s.seller_id
LEFT JOIN order_items AS oi ON oi.order_id=o.order_id
WHERE o.order_status IN ('Completed', 'Cancelled')
GROUP BY 1, 2, 3
ORDER BY 1)
SELECT seller_id, seller_name, 
 ROUND(sum(CASE WHEN order_status='Completed' THEN total_orders ELSE 0 END), 2) AS completed_orders,
 ROUND(sum(CASE WHEN order_status='Cancelled' THEN total_orders ELSE 0 END),2) AS cancelled_orders,
  sum(total_orders),
 ROUND(100*(sum(CASE WHEN order_status='Completed' THEN total_orders ELSE 0 END))/sum(total_orders),2) AS success_percent,
 ROUND(100*(sum(CASE WHEN order_status='Cancelled' THEN total_orders ELSE 0 END))/sum(total_orders),2) AS failed_percent
FROM seller_sales
GROUP BY 1, 2;


/* Q.12 Calculate the profit margin for each product (diff between price and cost of goods sold).
Challenge: Rank products by their margin, showing highest to lowest.
*/
-- Answer
SELECT p.product_id, ROUND(sum(p.cogs*oi.quantity)::NUMERIC,2) AS total_cost,  
			ROUND(sum(oi.total_sales)::NUMERIC,2) AS total_revenue,
			ROUND((sum(oi.total_sales)-sum(p.cogs*oi.quantity))::NUMERIC,2) AS profit,
		DENSE_RANK() OVER (ORDER BY (sum(oi.total_sales)-sum(p.cogs*oi.quantity)) DESC) AS ranking
FROM products AS p
RIGHT JOIN order_items AS oi ON p.product_id=oi.product_id
GROUP BY 1;


/* Q.13 Query the top 10 products by the number of returns.
Challenge: Display the return rate as a percentage of total units sold for each product.
*/
-- Answer
SELECT DISTINCT order_status
FROM orders;





